use apple_cf::{cf::CFDictionary, cm::CMSampleBuffer};
use videotoolbox::{
    available_video_encoder_details, available_video_encoder_details_with_options,
    supported_property_dictionary_for_encoder, Codec, CompressionSession, DecompressionSession,
    EncodedFrame, EncoderSupportedProperties, TaggedBufferGroup, VTError, VideoEncoderDetails,
    VideoEncoderListOptions, ffi,
};

const TARGET_FFI_SYMBOLS: &[&str] = &[
    "kVTAlphaChannelMode_PremultipliedAlpha",
    "kVTAlphaChannelMode_StraightAlpha",
    "kVTCameraCalibrationExtrinsicOriginSource_StereoCameraSystemBaseline",
    "kVTCameraCalibrationLensAlgorithmKind_ParametricLens",
    "kVTCameraCalibrationLensDomain_Color",
    "kVTCameraCalibrationLensRole_Left",
    "kVTCameraCalibrationLensRole_Mono",
    "kVTCameraCalibrationLensRole_Right",
    "kVTCompressionPreset_Balanced",
    "kVTCompressionPreset_HighQuality",
    "kVTCompressionPreset_HighSpeed",
    "kVTCompressionPreset_VideoConferencing",
    "kVTCompressionPropertyCameraCalibrationKey_ExtrinsicOrientationQuaternion",
    "kVTCompressionPropertyCameraCalibrationKey_ExtrinsicOriginSource",
    "kVTCompressionPropertyCameraCalibrationKey_IntrinsicMatrix",
    "kVTCompressionPropertyCameraCalibrationKey_IntrinsicMatrixProjectionOffset",
    "kVTCompressionPropertyCameraCalibrationKey_IntrinsicMatrixReferenceDimensions",
    "kVTCompressionPropertyCameraCalibrationKey_LensAlgorithmKind",
    "kVTCompressionPropertyCameraCalibrationKey_LensDistortions",
    "kVTCompressionPropertyCameraCalibrationKey_LensDomain",
    "kVTCompressionPropertyCameraCalibrationKey_LensFrameAdjustmentsPolynomialX",
    "kVTCompressionPropertyCameraCalibrationKey_LensFrameAdjustmentsPolynomialY",
    "kVTCompressionPropertyCameraCalibrationKey_LensIdentifier",
    "kVTCompressionPropertyCameraCalibrationKey_LensRole",
    "kVTCompressionPropertyCameraCalibrationKey_RadialAngleLimit",
    "kVTCompressionPropertyKey_AllowOpenGOP",
    "kVTCompressionPropertyKey_AllowTemporalCompression",
    "kVTCompressionPropertyKey_AlphaChannelMode",
    "kVTCompressionPropertyKey_AspectRatio16x9",
    "kVTCompressionPropertyKey_BaseLayerBitRateFraction",
    "kVTCompressionPropertyKey_BaseLayerFrameRate",
    "kVTCompressionPropertyKey_BaseLayerFrameRateFraction",
    "kVTCompressionPropertyKey_CalculateMeanSquaredError",
    "kVTCompressionPropertyKey_CameraCalibrationDataLensCollection",
    "kVTCompressionPropertyKey_CleanAperture",
    "kVTCompressionPropertyKey_ConstantBitRate",
    "kVTCompressionPropertyKey_ContentLightLevelInfo",
    "kVTCompressionPropertyKey_DataRateLimits",
    "kVTCompressionPropertyKey_Depth",
    "kVTCompressionPropertyKey_EnableLTR",
    "kVTCompressionPropertyKey_EncoderID",
    "kVTCompressionPropertyKey_EstimatedAverageBytesPerFrame",
    "kVTCompressionPropertyKey_ExpectedDuration",
    "kVTCompressionPropertyKey_FieldCount",
    "kVTCompressionPropertyKey_FieldDetail",
    "kVTCompressionPropertyKey_GammaLevel",
    "kVTCompressionPropertyKey_HDRMetadataInsertionMode",
    "kVTCompressionPropertyKey_HasLeftStereoEyeView",
    "kVTCompressionPropertyKey_HasRightStereoEyeView",
    "kVTCompressionPropertyKey_HeroEye",
    "kVTCompressionPropertyKey_HorizontalDisparityAdjustment",
    "kVTCompressionPropertyKey_HorizontalFieldOfView",
    "kVTCompressionPropertyKey_MVHEVCLeftAndRightViewIDs",
    "kVTCompressionPropertyKey_MVHEVCVideoLayerIDs",
    "kVTCompressionPropertyKey_MVHEVCViewIDs",
    "kVTCompressionPropertyKey_MasteringDisplayColorVolume",
    "kVTCompressionPropertyKey_MaxAllowedFrameQP",
    "kVTCompressionPropertyKey_MaxFrameDelayCount",
    "kVTCompressionPropertyKey_MaxH264SliceBytes",
    "kVTCompressionPropertyKey_MaxKeyFrameIntervalDuration",
    "kVTCompressionPropertyKey_MaximizePowerEfficiency",
    "kVTCompressionPropertyKey_MaximumRealTimeFrameRate",
    "kVTCompressionPropertyKey_MinAllowedFrameQP",
    "kVTCompressionPropertyKey_MoreFramesAfterEnd",
    "kVTCompressionPropertyKey_MoreFramesBeforeStart",
    "kVTCompressionPropertyKey_NumberOfPendingFrames",
    "kVTCompressionPropertyKey_OutputBitDepth",
    "kVTCompressionPropertyKey_PixelAspectRatio",
    "kVTCompressionPropertyKey_PixelBufferPoolIsShared",
    "kVTCompressionPropertyKey_PixelTransferProperties",
    "kVTCompressionPropertyKey_PreserveAlphaChannel",
    "kVTCompressionPropertyKey_PreserveDynamicHDRMetadata",
    "kVTCompressionPropertyKey_PrioritizeEncodingSpeedOverQuality",
    "kVTCompressionPropertyKey_ProgressiveScan",
    "kVTCompressionPropertyKey_ProjectionKind",
    "kVTCompressionPropertyKey_RecommendedParallelizationLimit",
    "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration",
    "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount",
    "kVTCompressionPropertyKey_ReferenceBufferCount",
    "kVTCompressionPropertyKey_SourceFrameCount",
    "kVTCompressionPropertyKey_SpatialAdaptiveQPLevel",
    "kVTCompressionPropertyKey_StereoCameraBaseline",
    "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount",
    "kVTCompressionPropertyKey_SupportedPresetDictionaries",
    "kVTCompressionPropertyKey_SupportsBaseFrameQP",
    "kVTCompressionPropertyKey_TargetQualityForAlpha",
    "kVTCompressionPropertyKey_UsingGPURegistryID",
    "kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder",
    "kVTCompressionPropertyKey_VBVBufferDuration",
    "kVTCompressionPropertyKey_VBVInitialDelayPercentage",
    "kVTCompressionPropertyKey_VBVMaxBitRate",
    "kVTCompressionPropertyKey_VariableBitRate",
    "kVTCompressionPropertyKey_VideoEncoderPixelBufferAttributes",
    "kVTCompressionPropertyKey_ViewPackingKind",
    "kVTEncodeFrameOptionKey_AcknowledgedLTRTokens",
    "kVTEncodeFrameOptionKey_BaseFrameQP",
    "kVTEncodeFrameOptionKey_ForceKeyFrame",
    "kVTEncodeFrameOptionKey_ForceLTRRefresh",
    "kVTHDRMetadataInsertionMode_Auto",
    "kVTHDRMetadataInsertionMode_None",
    "kVTHDRMetadataInsertionMode_RequestSDRRangePreservation",
    "kVTHeroEye_Left",
    "kVTHeroEye_Right",
    "kVTProjectionKind_Equirectangular",
    "kVTProjectionKind_HalfEquirectangular",
    "kVTProjectionKind_ParametricImmersive",
    "kVTProjectionKind_Rectilinear",
    "kVTSampleAttachmentKey_QualityMetrics",
    "kVTSampleAttachmentKey_RequireLTRAcknowledgementToken",
    "kVTSampleAttachmentQualityMetricsKey_ChromaBlueMeanSquaredError",
    "kVTSampleAttachmentQualityMetricsKey_ChromaRedMeanSquaredError",
    "kVTSampleAttachmentQualityMetricsKey_LumaMeanSquaredError",
    "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder",
    "kVTVideoEncoderSpecification_EnableLowLatencyRateControl",
    "kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID",
    "kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder",
    "kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID",
    "kVTViewPackingKind_OverUnder",
    "kVTViewPackingKind_SideBySide",
    "VTCompressionSessionEncodeFrameWithOutputHandler",
    "VTCompressionSessionEncodeMultiImageFrame",
    "VTCompressionSessionEncodeMultiImageFrameWithOutputHandler",
    "VTCompressionSessionOptionFlags",
    "VTIsStereoMVHEVCEncodeSupported",
    "kVTVideoEncoderSpecification_EncoderID",
    "kVTDecodeFrameOptionKey_ContentAnalyzerCropRectangle",
    "kVTDecodeFrameOptionKey_ContentAnalyzerRotation",
    "kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions",
    "kVTDecompressionPropertyKey_ContentHasInterframeDependencies",
    "kVTDecompressionPropertyKey_DecoderProducesRAWOutput",
    "kVTDecompressionPropertyKey_DeinterlaceMode",
    "kVTDecompressionPropertyKey_FieldMode",
    "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata",
    "kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded",
    "kVTDecompressionPropertyKey_MaximizePowerEfficiency",
    "kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded",
    "kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded",
    "kVTDecompressionPropertyKey_OnlyTheseFrames",
    "kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount",
    "kVTDecompressionPropertyKey_PixelBufferPool",
    "kVTDecompressionPropertyKey_PixelBufferPoolIsShared",
    "kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport",
    "kVTDecompressionPropertyKey_PixelTransferProperties",
    "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata",
    "kVTDecompressionPropertyKey_ReducedCoefficientDecode",
    "kVTDecompressionPropertyKey_ReducedFrameDelivery",
    "kVTDecompressionPropertyKey_ReducedResolutionDecode",
    "kVTDecompressionPropertyKey_RequestRAWOutput",
    "kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs",
    "kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers",
    "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance",
    "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality",
    "kVTDecompressionPropertyKey_ThreadCount",
    "kVTDecompressionPropertyKey_UsingGPURegistryID",
    "kVTDecompressionProperty_DeinterlaceMode_Temporal",
    "kVTDecompressionProperty_DeinterlaceMode_VerticalFilter",
    "kVTDecompressionProperty_FieldMode_BothFields",
    "kVTDecompressionProperty_FieldMode_BottomFieldOnly",
    "kVTDecompressionProperty_FieldMode_DeinterlaceFields",
    "kVTDecompressionProperty_FieldMode_SingleField",
    "kVTDecompressionProperty_FieldMode_TopFieldOnly",
    "kVTDecompressionProperty_OnlyTheseFrames_AllFrames",
    "kVTDecompressionProperty_OnlyTheseFrames_IFrames",
    "kVTDecompressionProperty_OnlyTheseFrames_KeyFrames",
    "kVTDecompressionProperty_OnlyTheseFrames_NonDroppableFrames",
    "kVTDecompressionProperty_TemporalLevelLimit",
    "kVTDecompressionResolutionKey_Height",
    "kVTDecompressionResolutionKey_Width",
    "kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder",
    "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID",
    "kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder",
    "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID",
    "VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler",
    "VTDecompressionSessionDecodeFrameWithOptions",
    "VTDecompressionSessionDecodeFrameWithOptionsAndOutputHandler",
    "VTDecompressionSessionDecodeFrameWithOutputHandler",
    "VTDecompressionSessionSetMultiImageCallback",
    "VTIsStereoMVHEVCDecodeSupported",
    "VTDecodeFrameFlags",
    "VTDecodeInfoFlags",
    "VTCopySupportedPropertyDictionaryForEncoder",
    "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders",
    "kVTVideoEncoderList_GPURegistryID",
    "kVTVideoEncoderList_InstanceLimit",
    "kVTVideoEncoderList_IsHardwareAccelerated",
    "kVTVideoEncoderList_PerformanceRating",
    "kVTVideoEncoderList_QualityRating",
    "kVTVideoEncoderList_SupportedSelectionProperties",
    "kVTVideoEncoderList_SupportsFrameReordering",
];

#[test]
fn targeted_ffi_gap_symbols_are_present() {
    let ffi_src = include_str!("../src/ffi/mod.rs");
    for symbol in TARGET_FFI_SYMBOLS {
        assert!(ffi_src.contains(symbol), "{symbol} missing from src/ffi/mod.rs");
    }
}

type EncodeMultiImageFn =
    fn(&CompressionSession, &TaggedBufferGroup, (i64, i32)) -> Result<EncodedFrame, VTError>;
type DecodeWithOptionsFn = fn(
    &DecompressionSession,
    &CMSampleBuffer,
    ffi::VTDecodeFrameFlags,
    Option<&CFDictionary>,
) -> Result<ffi::VTDecodeInfoFlags, VTError>;
type SetMultiImageCallbackFn = fn(
    &DecompressionSession,
    fn(videotoolbox::DecodedMultiImageFrame),
) -> Result<(), VTError>;
type EncoderDetailsFn = fn() -> Result<Vec<VideoEncoderDetails>, i32>;
type EncoderDetailsWithOptionsFn =
    fn(&VideoEncoderListOptions) -> Result<Vec<VideoEncoderDetails>, i32>;
type SupportedPropertyDictionaryFn =
    fn(i32, i32, Codec, Option<&str>) -> Result<EncoderSupportedProperties, i32>;

#[test]
fn new_safe_wrappers_are_reachable() {
    let encode_multi_image_fn: EncodeMultiImageFn = CompressionSession::encode_multi_image;
    let stereo_encode_support_fn: fn() -> bool = CompressionSession::is_stereo_mvhevc_encode_supported;
    let stereo_decode_support_fn: fn() -> bool = DecompressionSession::is_stereo_mvhevc_decode_supported;
    let decode_with_options_fn: DecodeWithOptionsFn = DecompressionSession::decode_with_options;
    let set_multi_image_callback_fn: SetMultiImageCallbackFn =
        DecompressionSession::set_multi_image_callback::<fn(videotoolbox::DecodedMultiImageFrame)>;
    let encoder_details_fn: EncoderDetailsFn = available_video_encoder_details;
    let encoder_details_with_options_fn: EncoderDetailsWithOptionsFn =
        available_video_encoder_details_with_options;
    let supported_property_dictionary_fn: SupportedPropertyDictionaryFn =
        supported_property_dictionary_for_encoder;
    let tagged_buffer_group_type_id_fn: fn() -> usize = TaggedBufferGroup::type_id;
    let tagged_buffer_group_len_fn: fn(&TaggedBufferGroup) -> usize = TaggedBufferGroup::len;

    let _ = (
        encode_multi_image_fn,
        stereo_encode_support_fn,
        stereo_decode_support_fn,
        decode_with_options_fn,
        set_multi_image_callback_fn,
        encoder_details_fn,
        encoder_details_with_options_fn,
        supported_property_dictionary_fn,
        tagged_buffer_group_type_id_fn,
        tagged_buffer_group_len_fn,
    );
}
